version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./config/realm-keycloak-angular-sandbox.json:/opt/keycloak/data/import/realm-keycloak-angular-sandbox.json:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
