# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:w
  - planning
  - committed
  - in-progress
  - pinned
  - security
  - critical
  - major
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been marked stale because it has not seen activity within
  three months. If you believe this to be in error, please use the 
  This issue will be closed within 15 days of being stale.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed due to continued inactivity. Thank you for your understanding.
  If you believe this to be in error, please contact one of the contributors 
  of the project.